<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup> 
    <PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" /> 
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260602" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\FFmpegSharp.csproj" />
  </ItemGroup>

</Project>
