<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>
 
    <ItemGroup>
        <PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" />
    </ItemGroup>


</Project>
